PRODUCT_SOONG_NAMESPACES += device/axion/common/platform/lahaina

# Disable kernel Modules for 4.14 and 4.19
AXION_KERNEL_MODULES_BINDER_UX_HOOKS := n
AXION_KERNEL_MODULES_BINDER_OBS_HOOKS := n
AXION_KERNEL_MODULES_SCHED_RQ_HOOKS := n
AXION_KERNEL_MODULES_SCHED_NOCHECK := n
AXION_KERNEL_MODULES_TASK_TRACEPOINTS := n
AXION_KERNEL_MODULES_AFFINITY_GUARD_HOOK := n
AXION_KERNEL_MODULES_UCLAMP_EFF_HOOK := n
AXION_KERNEL_MODULES_MAP_UTIL_FREQ_HOOK := n
AXION_KERNEL_MODULES_AX_BOOST := n
AXION_KERNEL_MODULES_ATCM := n
AXION_KERNEL_MODULES_GAME_BOOST := n
AXION_KERNEL_MODULES_AX_BOOST_GPU_PROVIDER := n
AXION_KERNEL_MODULES_AX_BOOST_MEMLAT_PROVIDER := n
AXION_KERNEL_MODULES_AX_BOOST_DDR_PROVIDER := n
AXION_KERNEL_MODULES_AX_BOOST_L3_PROVIDER := n

include device/axion/common/config/board/common.mk
